#!/usr/bin/env python3
"""Writes plugin*.properties and messages*.properties of the UI bundle from
the language modules in this folder. English is the fallback (no suffix).

Run: python3 releng/i18n/generate.py
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
UI = os.path.join(HERE, "..", "..", "bundles", "de.kiliantaubmann.bella.ui")
LANGS = ["en", "de", "fr", "es", "it", "pt_BR", "nl", "pl", "cs", "tr", "ru", "zh_CN", "ja", "ko"]


def load(lang):
    spec = importlib.util.spec_from_file_location(lang, os.path.join(HERE, lang + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def escape(value):
    # Unicode escapes keep the files readable by every properties loader.
    out = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ord(ch) > 126:
            out.append("\\u%04x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def write(path, entries, header):
    with open(path, "w", encoding="ascii", newline="\n") as f:
        f.write("# " + header + "\n# Generated by releng/i18n/generate.py - edit the .py sources, not this file.\n")
        for k, v in entries.items():
            f.write(k + "=" + escape(v) + "\n")


def main():
    en = load("en")
    errors = []
    for lang in LANGS:
        mod = load(lang)
        for name in ("PLUGIN", "MESSAGES"):
            ref = getattr(en, name)
            got = getattr(mod, name)
            missing = set(ref) - set(got)
            extra = set(got) - set(ref)
            if missing or extra:
                errors.append(f"{lang}.{name}: missing {sorted(missing)} extra {sorted(extra)}")
            for k, v in got.items():
                if "'" in v:
                    errors.append(f"{lang}.{name}.{k}: ASCII apostrophe, use ’")
                for n in range(3):
                    if ("{%d}" % n in ref.get(k, "")) != ("{%d}" % n in v):
                        errors.append(f"{lang}.{name}.{k}: placeholder {{{n}}} mismatch")
        suffix = "" if lang == "en" else "_" + lang
        write(os.path.join(UI, "plugin" + suffix + ".properties"), mod.PLUGIN, "Bella UI - " + lang)
        write(os.path.join(UI, "src", "de", "kiliantaubmann", "bella", "ui", "messages" + suffix + ".properties"),
              mod.MESSAGES, "Bella UI - " + lang)
    if errors:
        print("\n".join(errors))
        sys.exit(1)
    print("wrote", len(LANGS), "languages")


if __name__ == "__main__":
    main()
