source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               plugin.xml,\
               plugin.properties,\
               plugin_*.properties,\
               icons/,\
               html/,\
               about.ini
